name: И Robot Framework - Testes Automatizados

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout do reposit贸rio
        uses: actions/checkout@v4

      - name:  Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name:  Instalar depend锚ncias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name:  Instalar Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: 讹 Executar testes Robot Framework
        # Usamos o ponto . para garantir que ele procure em todas as pastas
        run: |
          robot -d results .
        continue-on-error: true # Garante que os relat贸rios sejam gerados mesmo se um teste falhar

      - name:  Publicar resumo no Workflow
        if: always()
        run: |
          echo "## И Resultado dos Testes Robot Framework" >> $GITHUB_STEP_SUMMARY
          echo "Os logs detalhados est茫o dispon铆veis nos Artifacts e no GitHub Pages." >> $GITHUB_STEP_SUMMARY

      - name:  Publicar Artifact do relat贸rio
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-report
          path: results/

      - name:  Publicar relat贸rio no GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: results